create table if not exists ai_comment_job (
  id bigint generated by default as identity primary key,
  post_id bigint not null,
  provider_code varchar(64) not null,
  status varchar(16) not null default 'PENDING',
  attempts int not null default 0,
  next_retry_at timestamp not null,
  last_error varchar(500),
  comment_id bigint,
  processed_at timestamp,
  created_at timestamp not null,
  updated_at timestamp not null,
  constraint fk_ai_comment_job_post foreign key (post_id) references plaza_post(id)
);

create unique index if not exists uk_ai_comment_job_post_provider on ai_comment_job(post_id, provider_code);
create index if not exists idx_ai_comment_job_status_retry on ai_comment_job(status, next_retry_at, created_at);
