create table if not exists ai_task_draft (
  id bigint generated by default as identity primary key,
  provider_code varchar(64) not null,
  title varchar(128) not null,
  content text not null,
  category varchar(32),
  location_text varchar(256),
  amount decimal(10,2) not null,
  total_slots int not null,
  deadline_at timestamp not null,
  proof_requirements varchar(256),
  status varchar(32) not null,
  published_task_no varchar(32),
  raw_response text,
  created_at timestamp not null,
  updated_at timestamp not null
);

create index if not exists idx_ai_task_draft_created_at on ai_task_draft(created_at desc);
