create table if not exists ai_music_like (
  id bigint generated by default as identity primary key,
  music_id bigint not null,
  user_id bigint not null,
  created_at timestamp,
  updated_at timestamp,
  constraint fk_ai_music_like_music foreign key (music_id) references ai_music_job(id),
  constraint fk_ai_music_like_user foreign key (user_id) references user_account(id),
  constraint uk_ai_music_like unique (music_id, user_id)
);

update plaza_ai_provider
set logo_text = '智'
where upper(code) = 'GLM' and (logo_text is null or logo_text = '' or logo_text = 'G');
