package com.leiyang.anontask.domain.enums;

public enum WalletFlowType {
  RECHARGE,
  TASK_REWARD,
  TASK_PUBLISH_FREEZE,
  TASK_PUBLISH_SETTLE,
  TASK_PUBLISH_UNFREEZE,
  MUSIC_TIP_OUT,
  MUSIC_TIP_IN,
  MUSIC_GENERATE_PAY,
  MUSIC_PACKAGE_BUY,
  WITHDRAW_APPLY_FREEZE,
  WITHDRAW_PAID,
  WITHDRAW_REJECT_UNFREEZE
}
